services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tts
    networks:
      artwalk-net:
        aliases:
          - backend
    volumes:
      - ./shared-data:/app/shared-data   # <-- Lokaler Ordner shared-data wird in Container gemappt

  tts:
    build:
      context: ./tts_service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    networks:
      artwalk-net:
        aliases:
          - tts
    volumes:
      - ./shared-data:/app/shared-data   # <-- Gleiches Volume auch im TTS Container

networks:
  artwalk-net:
    driver: bridge

