[tool.poetry]
name = "tts_service"
version = "0.1.0"
description = ""
authors = ["Du"]
packages = [{ include = "tts_service" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
TTS = "^0.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
