artist_task:
  description: >
    Research the artist "{{artist}}" and their artwork "{{artwork}}".
    Provide a short biography, general artistic style, and key themes in their work.
  expected_output: >
    - Short artist bio
    - Artistic style
    - Notable themes or ideas in the artwork
  agent: art_researcher

image_task:
  description: >
   Using the following description of the artwork "{{artwork}}" by "{{artist}}", analyze the visual elements and provide an interpretation.
    Description: "{{description}}"
  expected_output: >
    - Visual description
    - Emotional or symbolic interpretation
  agent: image_analyst

era_task:
  description: >
   Based on the artist "{{artist}}" and the artwork "{{artwork}}", determine the historical art period.
    Include timeframe, movement name, and key traits of the era.
  expected_output: >
    - Art movement or era
    - Approximate years
    - Characteristics of the era
  agent: era_expert


similarity_task:
  description: >
   Suggest 3 similar artworks or artists that share stylistic, thematic, or emotional qualities with "{{artwork}}" by "{{artist}}".
  expected_output: >
    - List of 3 artworks or artists
    - Short explanation of similarity
  agent: similarity_curator


reporting_task:
  description: >
    Create a detailed, structured report that combines all findings from the previous tasks.
    Include:
    - Artist biography and artistic style
    - Visual description and interpretation of the artwork
    - Historical art movement and key traits
    - Wikidata facts (year, image URL, etc.)
    - Suggested similar artworks or artists

    Return the result as a JSON object with clearly labeled sections.
  expected_output: >
    - JSON file with structure:
      {
        "artist_info": {
          "name": "...",
          "biography": "...",
          "style": "..."
        },
        "artwork_analysis": "...",
        "historical_context": "...",
        "wikidata_facts": {
          "year": "...",
          "image_url": "...",
          ...
        },
        "similar_artworks": ["...", "..."]
      }
  agent: reporting_analyst
  output_file: final_art_report.json




